num = int(input())

print('{} x {} = {}'.format (num, 1, num*1))
print('{} x {} = {}'.format (num, 2, num*2))
print('{} x {} = {}'.format (num, 3, num*3))
print('{} x {} = {}'.format (num, 4, num*4))
print('{} x {} = {}'.format (num, 5, num*5))
print('{} x {} = {}'.format (num, 6, num*6))
print('{} x {} = {}'.format (num, 7, num*7))
print('{} x {} = {}'.format (num, 8, num*8))
print('{} x {} = {}'.format (num, 9, num*9))
print('{} x {} = {}'.format (num, 10, num*10))


N = int(input())

print(N, 'X 1 =', N)
print(N, 'X 2 =', N*2)
print(N, 'X 3 =', N*3)
print(N, 'X 4 =', N*4)
print(N, 'X 5 =', N*5)
print(N, 'X 6 =', N*6)
print(N, 'X 7 =', N*7)
print(N, 'X 8 =', N*8)
print(N, 'X 9 =', N*9)
print(N, 'X 10 =', N*10)